name: Scheduled_health_check_CI

on:
  push:
    branches:
      - master

jobs:
  simple_health_check:
    runs-on: ubuntu-20.04

    steps:
      - name: Check system health
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://fullstack-pokemon.fly.dev/health